# version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/generated-images:/app/generated-images
    restart: unless-stopped
    working_dir: /app
    environment:
      MAX_TASKS_PER_CARD: ${MAX_TASKS_PER_CARD:-25}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    working_dir: /app
