import { useEffect, useState } from 'react';
import api from '../api';

export default function ItemRequests() {
  const [requests, setRequests] = useState([]); const [error, setError] = useState('');
  const load = async () => { try { setRequests((await api.get('/item-requests')).data); setError(''); } catch (err) { setError(err.response?.data?.error || 'Unable to load item requests.'); } };
  useEffect(() => { load(); }, []);
  const update = async (id, status) => { try { await api.put(`/item-requests/${id}`, { status }); await load(); } catch (err) { setError(err.response?.data?.error || 'Unable to update this request.'); } };
  return <div className="max-w-6xl mx-auto space-y-6"><div><h1 className="text-2xl font-bold text-orange-500">Item Requests</h1><p className="text-sm text-slate-400">Requests submitted by technicians through Telegram.</p></div>{error && <p className="text-sm text-red-400">{error}</p>}<div className="overflow-x-auto rounded-xl border border-slate-700"><table className="w-full text-sm"><thead className="bg-slate-800 text-left text-slate-400"><tr>{['ID', 'Technician Name', 'Case Number', 'Item Description', 'Status', 'Requested At', 'Actions'].map((item) => <th key={item} className="px-4 py-3">{item}</th>)}</tr></thead><tbody>{requests.length ? requests.map((request) => <tr key={request.id} className="border-t border-slate-700"><td className="px-4 py-3">{request.id}</td><td className="px-4 py-3">{request.technician_name}</td><td className="px-4 py-3">{request.case_number || '—'}</td><td className="px-4 py-3">{request.item_description}</td><td className="px-4 py-3 capitalize">{request.status}</td><td className="px-4 py-3 text-slate-400">{request.requested_at ? new Date(request.requested_at).toLocaleString() : '—'}</td><td className="px-4 py-3">{request.status === 'pending' && <div className="flex gap-2"><button onClick={() => update(request.id, 'approved')} className="rounded bg-green-600 px-2 py-1 text-xs">Approve</button><button onClick={() => update(request.id, 'rejected')} className="rounded bg-red-600 px-2 py-1 text-xs">Reject</button></div>}</td></tr>) : <tr><td colSpan="7" className="px-4 py-8 text-center text-slate-400">No item requests yet.</td></tr>}</tbody></table></div></div>;
}
